spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.208.234.10:3306/zhaipz?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
logging:
  level:
    src.main: info
server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapping/*.xml